### ISSUE TITLE
add description, travis, coveralls, etc.

### ISSUE THREAD

**Issue by jchlapinski** [kodegenix/kg-js#1]

**Comment by maksymilianciak** [comment]
* https://github.com/kodegenix/kg-js/commit/077f6c190ae93c9b9529977ef1ca19f5309c256e
* https://github.com/kodegenix/kg-js/commit/dcf50ad8cad7a14feedc09eb3665915e53d845ff + https://github.com/kodegenix/kg-js/commit/45ca670bcbe80c852617adf4d4f6a297ed132d6b
* https://github.com/kodegenix/kg-js/commit/8134faf8335cdd82bba004d0d8fe45878c6b5c69 (Codecov instead of Coveralls)
